jofedigital 2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductUserController;
use App\Http\Controllers\CategoryUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth', 'is_admin'])->group(function () {

    Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

    Route::view('profile','profile')->name('profile');
    Route::resource('products', ProductController::class);
    Route::resource('categories', CategoryController::class);
});

Route::resource('productsUser', ProductUserController::class);
Route::resource('categoriesUser', CategoryUserController::class);

jofedigital 2/resources/views/adminHome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    @if(Auth::user()->is_admin == 1)
                    <div class="card">
                        <div class="card-body">
                              <a class="nav-link" href="{{ url('products')  }}">{{ __('Les Produits') }}</a>
                       </div>
                    </div>

                    <div class="card">
                        <div class="card-body">
                              <a class="nav-link" href="{{ url('categories')  }}">{{ __('Les Categories') }}</a>
                       </div>
                    </div>

                    @else

                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

jofedigital 2/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">

                    @if(Auth::user()->is_admin == 1)

                    @else
                    <div class="card">
                        <div class="card-body">
                              <a class="nav-link" href="{{ url('productsUser')  }}">{{ __('Les Produits') }}</a>
                       </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

jofedigital 2/resources/views/index.blade.php
@extends('products.layout')

@section('content')
    <div class="row pt-5 mt-5">
        <div class="col-lg-12 margin-tb pt-5 mt-5">
            <div class="pull-left pt-5 mt-5" style="margin-top:5%">
                <h2>La liste de ventes d'article</h2>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered " style="margin-top:5%">
        <tr>
            <th>No</th>
            <th>Nom</th>
            <th>Détails</th>
            <!-- <th>Category</th> -->
        </tr>
        @foreach ($products as $product)

        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $product->name }} <img src="/storage/images/{{$product->image}}" style="height:100px; width:100px"> </td>
            <td>{{ $product->detail }}</td>
            <!-- <td>{{ $product->category }}</td> -->


        </tr>

        @endforeach
    </table>

    {!! $products->links() !!}

@endsection

jofedigital 2/resources/views/indexUser.blade.php
@extends('categories.layout')

@section('content')
    <div class="row pt-5 mt-5">
        <div class="col-lg-12 margin-tb pt-5 mt-5">
            <div class="pull-left pt-5 mt-5" style="margin-top:5%">
                <h2>La liste des categories de ventes d'article</h2>
            </div>
            <div class="pull-right" style="margin-top:5%">
                <a class="btn btn-success" href="{{ route('categories.create') }}"> Ajouter une nouvelle categorie </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered " style="margin-top:5%">
        <tr>
            <th>No</th>
            <th>Categorie</th>
            <th>Categorie</th>
            <th width="380px">Action</th>
        </tr>
        @foreach ($categories as $category)
        @foreach ($products as $product)

        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $category->id }}</td>
            <td>{{ $product->id }}</td>
            <td>
            </td>
        </tr>
        @endforeach

        @endforeach
    </table>

    {!! $categories->links() !!}

@endsection

jofedigital 2/resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
      <li>
        {{$error}}
      </li>
      @endforeach
    </ul>
   </div>
  @endif
  @if(session()->get('message'))
  <div class="alert alert-success" role="alert">
    <strong>Success: </strong>{{session()->get('message')}}
  </div>
  @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{Auth::user()->name}}'s Profile</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if($message = Session::get('success'))
                      <div class="alert alert-success">
                   <p>{{$message}}</p>
                      </div>
                   @endif
                    <form action="{{route('home')}}" method="POST">
                    @csrf
                       <div class="form-group">
                           <label for="name"><strong>Name:</strong></label>
                           <input type="text" class="form-control" id ="name" name="name" value="{{Auth::user()->name}}">
                       </div>
                        <div class="form-group">
                           <label for="email"><strong>Email:</strong></label>
                           <input type="text" class="form-control" id ="email" value="{{Auth::user()->email}}" name="email">
                       </div>
                        <button class="btn btn-primary" type="submit">Update Profile</button>
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection